from pydantic import BaseModel, Field

# The main model(output presentation)
class CVModel(BaseModel):
    cv_id: str
    candidate_name: str
    cv_summary: str = Field(None, description="The summary of the candidate's CV, generated by the model.")
